[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
example = "56Hf5PcrNpJ9z94MczM2iWymqP8oR7pxAtRirveQqCPv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/catmcgee/Documents/work/card_shuffler_api/programs/example/artifacts/arcium_program_0.3.0.so"

[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7MGSS4iKNM4sVib7bDZDJhVqB6EcchPwVnTKenCY1jt3"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "RfDque7sQmUrahfDAhjva1FAequPw2EfRwkp7jQnWMp"
filename = "artifacts/wallet_acc_RfDq_nWMp.json"

[[test.validator.account]]
address = "6XuDUYa9hZs65RzH3YYHH7qtm5xMzVhvqmG165ER4abh"
filename = "artifacts/arx_ata_RfDq_nWMp.json"

[[test.validator.account]]
address = "G4ZynwtKABW6VRjX8wACFezTDu8bH3NDgwcguDkuKtQz"
filename = "artifacts/wallet_acc_G4Zy_KtQz.json"

[[test.validator.account]]
address = "9rbNuFkUiHbkMGWUpTEFCHxm1QWqiX4kc3MLiJF48cY1"
filename = "artifacts/wallet_acc_callback_9rbN_8cY1.json"

[[test.validator.account]]
address = "FDUb79myLxXs6CE6GyHmERcGSPoVGnsFCM3n1Rg4NH7S"
filename = "artifacts/arx_ata_G4Zy_KtQz.json"

[[test.validator.account]]
address = "CEBuy4oAMvx9dnT134hP81oDMZMQeacp98rzm88odThH"
filename = "artifacts/operator_acc_G4Zy_KtQz.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_G4Zy_KtQz.json"

[[test.validator.account]]
address = "FZwwYtoHp7amre7nfjTDQhD9B747VGB7Yprk9xeHvJ1f"
filename = "artifacts/wallet_acc_FZww_vJ1f.json"

[[test.validator.account]]
address = "75B56MgayAUpLMANdtW6qJJWq5Kp47wEUnRCz4uTuBdX"
filename = "artifacts/wallet_acc_callback_75B5_uBdX.json"

[[test.validator.account]]
address = "9Nnimt1oeAeke3HbzUwVPcto9mHLdCTqX3dB5YT5mtM9"
filename = "artifacts/arx_ata_FZww_vJ1f.json"

[[test.validator.account]]
address = "FQRdZCnKWj95DfgrXpHUfm2zop2gnU5CE6mD76gsBubA"
filename = "artifacts/operator_acc_FZww_vJ1f.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_FZww_vJ1f.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"
