[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shuffle_deal = "9heUwYsyauSVrMwv3kULC93Ck35WxWyG6EDqcrfJ5me"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/catmcgee/Documents/work/card_shuffler_api/arcium_jobs/shuffle_deal/artifacts/arcium_program_0.3.0.so"
